version: '3.8'

services:
  frontend:
    build: ./Frontend/app/
    ports:
      - "3001:80"
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "5555:5555"
    environment:
      DB_HOST: localhost
      DB_PORT: 3307
      DB_USER: root
      DB_PASSWORD: root1234
      DB_NAME: testbaza
    depends_on:
      - db

  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: testbaza
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
